# Change the name of this file to configuration.conf
NOTIFICATION_EMAIL="daniele.scalabrini@studenti.unipr.it" # Insert your e-mail address to receive notifications when the job starts, ends, etc.
JULIA_FOLDER_PATH="/hpc/home/daniele.scalabrini/CPN/CPN_Lang_Lattice" # Change this to the whole path to the root folder of the code
SITE_ENERGY_PATH="/hpc/archive/G_LGT/cpn_nspt/cpn_Lang" # Change this to the path where the .mat file with the energy site-per-site needs to be saved
